# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(549, 513)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_61 = QtWidgets.QFrame(self.centralwidget)
        self.frame_61.setGeometry(QtCore.QRect(10, 10, 500, 480))
        self.frame_61.setMinimumSize(QtCore.QSize(500, 480))
        self.frame_61.setMaximumSize(QtCore.QSize(10000, 10000))
        self.frame_61.setAutoFillBackground(False)
        self.frame_61.setStyleSheet("background-color: rgb(197, 197, 197);\n"
"")
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_61)
        self.verticalLayout_30.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_64 = QtWidgets.QFrame(self.frame_61)
        self.frame_64.setMinimumSize(QtCore.QSize(515, 60))
        self.frame_64.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_64.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_64.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_64.setObjectName("frame_64")
        self.label_158 = QtWidgets.QLabel(self.frame_64)
        self.label_158.setGeometry(QtCore.QRect(0, 0, 491, 51))
        font = QtGui.QFont()
        font.setFamily("HoloLens MDL2 Assets")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_158.setFont(font)
        self.label_158.setStyleSheet("padding-left:10px;\n"
"border-bottom:1px solid black;\n"
"border-bottom-left-radius: 0px;\n"
"border-bottom-right-radius: 0px;")
        self.label_158.setAlignment(QtCore.Qt.AlignCenter)
        self.label_158.setObjectName("label_158")
        self.verticalLayout_30.addWidget(self.frame_64)
        self.frame_65 = QtWidgets.QFrame(self.frame_61)
        self.frame_65.setMinimumSize(QtCore.QSize(0, 280))
        self.frame_65.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_65.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_65.setObjectName("frame_65")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.frame_65)
        self.lineEdit_23.setGeometry(QtCore.QRect(20, 20, 321, 31))
        self.lineEdit_23.setStyleSheet("border:1.2px solid black;\n"
"border-radius:3px;\n"
"padding-left:10px")
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_159 = QtWidgets.QLabel(self.frame_65)
        self.label_159.setGeometry(QtCore.QRect(20, 0, 351, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_159.setFont(font)
        self.label_159.setStyleSheet("")
        self.label_159.setObjectName("label_159")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_65)
        self.pushButton_18.setGeometry(QtCore.QRect(350, 20, 121, 31))
        self.pushButton_18.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_18.setStyleSheet("border: 1px solid black;\n"
"border-radius: 3px;\n"
"background-color: rgb(9, 204, 6);\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_65)
        self.pushButton_19.setGeometry(QtCore.QRect(30, 350, 101, 41))
        self.pushButton_19.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_19.setStyleSheet("background-color: rgb(1, 79, 223);\n"
"border: 1px solid black;\n"
"border-radius: 3px;")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_65)
        self.pushButton_20.setGeometry(QtCore.QRect(350, 350, 111, 41))
        self.pushButton_20.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_20.setStyleSheet("border: 1px solid black;\n"
"border-radius: 3px;\n"
"background-color: rgb(9, 204, 6);\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.frame_56 = QtWidgets.QFrame(self.frame_65)
        self.frame_56.setGeometry(QtCore.QRect(20, 70, 451, 251))
        self.frame_56.setMinimumSize(QtCore.QSize(451, 251))
        self.frame_56.setStyleSheet("border:1px solid black;\n"
"border-radius:3px")
        self.frame_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_56)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_160 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_160.setFont(font)
        self.label_160.setStyleSheet("border: 1px solid rgb(12, 12, 234);\n"
"border-radius:3px\n"
"")
        self.label_160.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_160.setObjectName("label_160")
        self.gridLayout_3.addWidget(self.label_160, 1, 1, 1, 1)
        self.label_161 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_161.setFont(font)
        self.label_161.setStyleSheet("border: 1px solid rgb(12, 12, 234);\n"
"border-radius:3px\n"
"")
        self.label_161.setText("")
        self.label_161.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_161.setObjectName("label_161")
        self.gridLayout_3.addWidget(self.label_161, 0, 1, 1, 1)
        self.label_162 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_162.setFont(font)
        self.label_162.setStyleSheet("border: 1px solid rgb(12, 12, 234);\n"
"border-radius:3px\n"
"")
        self.label_162.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_162.setObjectName("label_162")
        self.gridLayout_3.addWidget(self.label_162, 0, 0, 1, 1)
        self.label_163 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_163.setFont(font)
        self.label_163.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius:3px\n"
"\n"
"\n"
"")
        self.label_163.setText("")
        self.label_163.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_163.setObjectName("label_163")
        self.gridLayout_3.addWidget(self.label_163, 2, 1, 1, 1)
        self.label_164 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_164.setFont(font)
        self.label_164.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius:3px\n"
"\n"
"\n"
"")
        self.label_164.setText("")
        self.label_164.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_164.setObjectName("label_164")
        self.gridLayout_3.addWidget(self.label_164, 2, 0, 1, 1)
        self.label_165 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_165.setFont(font)
        self.label_165.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius:3px\n"
"\n"
"\n"
"")
        self.label_165.setText("")
        self.label_165.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_165.setObjectName("label_165")
        self.gridLayout_3.addWidget(self.label_165, 1, 0, 1, 1)
        self.label_166 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_166.setFont(font)
        self.label_166.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius:3px\n"
"\n"
"\n"
"")
        self.label_166.setText("")
        self.label_166.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_166.setObjectName("label_166")
        self.gridLayout_3.addWidget(self.label_166, 3, 1, 1, 1)
        self.label_167 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_167.setFont(font)
        self.label_167.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius:3px\n"
"\n"
"\n"
"")
        self.label_167.setText("")
        self.label_167.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_167.setObjectName("label_167")
        self.gridLayout_3.addWidget(self.label_167, 3, 0, 1, 1)
        self.label_168 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_168.setFont(font)
        self.label_168.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius:3px\n"
"\n"
"\n"
"")
        self.label_168.setText("")
        self.label_168.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_168.setObjectName("label_168")
        self.gridLayout_3.addWidget(self.label_168, 4, 0, 1, 1)
        self.label_169 = QtWidgets.QLabel(self.frame_56)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_169.setFont(font)
        self.label_169.setStyleSheet("border: 1px solid rgb(197, 197, 197);\n"
"border-radius:3px\n"
"\n"
"\n"
"")
        self.label_169.setText("")
        self.label_169.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_169.setObjectName("label_169")
        self.gridLayout_3.addWidget(self.label_169, 4, 1, 1, 1)
        self.verticalLayout_30.addWidget(self.frame_65)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_158.setText(_translate("MainWindow", "Skills"))
        self.lineEdit_23.setPlaceholderText(_translate("MainWindow", "Programming | Data analysis | Database administration"))
        self.label_159.setText(_translate("MainWindow", "Add skills. This improves your chances of getting a job"))
        self.pushButton_18.setText(_translate("MainWindow", "Add skill"))
        self.pushButton_19.setText(_translate("MainWindow", "Back"))
        self.pushButton_19.setShortcut(_translate("MainWindow", "Return"))
        self.pushButton_20.setText(_translate("MainWindow", "Next"))
        self.label_160.setText(_translate("MainWindow", "Database programming in python and SQL"))
        self.label_162.setText(_translate("MainWindow", "Database programming in python and SQL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
